name: Jekyll site CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the site in the jekyll/builder container
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:latest /bin/bash -c "chmod -R 777 /srv/jekyll && jekyll build --future"

    - name: Dockerize
      if: success()
      uses: manusa/actions-publish-docker@v1.1.2
      with:
       name: ktoddsd/kevintodd
       username: ${{ secrets.DOCKER_HUB_USER }}
       password: ${{ secrets.DOCKER_HUB_PASSWORD }}


