# Upon creating a new release and publishing it in GitHub, this workflow will kick off

name: Publish Docker image & Deploy to AKS

on:
  release:
    types: [published]

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ktoddsd/kevintodd.net
      
      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          
#Set Kubernetes context (Azure AKS)
      - uses: azure/aks-set-context@v1
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}' # Azure credentials
          resource-group: 'kevintodd-net'
          cluster-name: 'kevintodd-net'
        id: login

# Deploy to Azure AKS using kubernetes
      - uses: Azure/k8s-deploy@v1
        with:
         namespace: default
       #Specify what manifest file or files to use
         manifests: |
          .manifests/deployment.yaml
          .manifests/service.yaml
        #This will replace any image in manifest files with this 
        #specific version
         images: |
          index.docker.io/ktoddsd/kevintodd.net:latest
